#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

##### AUTOSTART ####
#dunst --config $HOME/.config/dunst/dunstrc &
#nitrogen --restore &
feh --bg-scale $HOME/Pictures/Wallpaper/wallpaper.jpg &
picom --config $HOME/.config/picom/picom.conf &
tint2 &
wmname LG3D
sh $HOME/.config/polybar/launch.sh
sh $HOME/Scripts/date.sh
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# launch drop down terminal if it's not running already
ddterm_cmd="st -n ddterm -e tmux new-session -A -s ddterm"
if ! pgrep -U ${USER:-$(whoami)} -f "st -n ddterm" >/dev/null; then
    bspc rule -a st-256color:ddterm state=floating sticky=on rectangle=1920x588+-$bw+-$bw
    $ddterm_cmd &
    sleep .1
    DDTERMWID="$(bspc query --nodes --node newest.floating.sticky)"
    export DDTERMWID
fi

#### GENERAL ###
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           10

bspc config normal_border_color  "#282828"
bspc config active_border_color  "#282828"
bspc config focused_border_color "#32302f"

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config click_to_focus        none
bspc config focus_follows_pointer true

bspc config pointer_modifier mod4
bspc config pointer_action1 move 
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
#### WINDOW RULES ####
bspc rule -a Gimp 	            state=floating  desktop='^8'  follow=on 	
bspc rule -a xdman-Main	        state=floating
bspc rule -a Galculator         state=floating
bspc rule -a mplayer2 		    state=floating
bspc rule -a Org.gnome.Nautilus state=floating
bspc rule -a jetbrains-toolbox  state=floating
bspc rule -a Java		        state=floating
bspc rule -a Pavucontrol 	    state=floating
bspc rule -a eog 	            state=floating
bspc rule -a Steam 	            state=floating
bspc rule -a Guake 	            state=floating
bspc rule -a Cawbird            state=floating
